sudo: false
language: scala

scala:
  - 2.12.7

jdk:
  - oraclejdk8

jobs:
  include:
  - stage: verify

    before_script:

    script:
    - sbt coverage "++$TRAVIS_SCALA_VERSION test"

    after_success:
    - sbt ++$TRAVIS_SCALA_VERSION "++$TRAVIS_SCALA_VERSION coverageReport" coverageAggregate codacyCoverage


cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt